### PR TITLE
Fix links v2

### LINKED ISSUE #51: too many links produce 404s
Too many pages link to old/dead/moved content and produce 404s.
- [x] http://www.irchelp.org/irchelp/clients/unix/ircii/
- [ ] http://www.irchelp.org/irchelp/clients/unix/ircii/irciiman.wri -> 404
- [ ] http://www.irchelp.org/irchelp/clients/unix/security/fwfaq.html -> 404
- [ ] http://www.irchelp.org/irchelp/clients/unix/ircii/commands/ -> 404

etc

### PR DESCRIPTION
**Pull request by sgstair**
This request replaces #91 to resolve #51 - [The script to automatically fix issues](https://github.com/sgstair/wio/blob/fix_links_script/fixlinks.ps1) has been substantially improved. It still doesn't get everything though.

This PR automatically fixes most of the broken links on the site. A few things it does not fix:
* Some of the pages that need redirect_from do not have headers. These were not added
* Pages linked in the navbar did not automatically get a redirect_from, and some of those are incorrect.

The log from my script run is [here](https://gist.github.com/sgstair/18aeb942af0d2f8274af18e288948fdf)
Summary information and missing headers:
```
Done. Wrote 44 files (12 errors, 100 URL changes, 7 redirects added)

Redirect could not be added to the following files:
/misc/foreign.md (redirect_from: /irchelp/misc/foreign.html)
/misc/ptnew2irc.md (redirect_from: /irchelp/misc/ptnew2irc.html)
/misc/trnew2irc.md (redirect_from: /irchelp/misc/trnew2irc.html)
/misc/why_do_people_register.md (redirect_from: /irchelp/misc/why_do_people_register.html)
/networks/nets/big4.md (redirect_from: /irchelp/networks/nets/big4.html)
/networks/nets/local.md (redirect_from: /irchelp/networks/nets/local.html)
/networks/nets/medium.md (redirect_from: /irchelp/networks/nets/medium.html)
/networks/nets/small.md (redirect_from: /irchelp/networks/nets/small.html)
/networks/nets/subject.md (redirect_from: /irchelp/networks/nets/subject.html)
/networks/servers/efnet.md (redirect_from: /irchelp/networks/servers/efnet.html)
/nuke/report.md (redirect_from: /irchelp/nuke/report.html)
/nuke/trace.md (redirect_from: /irchelp/nuke/trace.html)
```

### CODE REVIEW

**Comment by wilhelmy** [comment]
I reenabled html-proofer and it seems we still have a bunch of invalid links. You can find the list here: https://travis-ci.org/irchelp/wio/jobs/504280141#L686

**Comment by sgstair** [comment]
Most of the expressed warnings are repetitions from the navbar, some of which are my fault. I'm working on fixing this at the moment, and will see what I can do with the other warnings, but there are just a lot of content errors from what I'm seeing so far.

**Comment by sgstair** [comment]
Another note - Those warnings are not apparently considering any redirect_from, so they might still be largely ok and not actually broken links. It's hard to tell. I just ran into one that definitely did have a proper redirect_from

**Comment by wilhelmy** [comment]
Hm, odd. AFAIK the redirect_from directive works by generating a file in the location that's being redirected from, which issues a redirect in the browser, which means there's a HTML file being generated which the final html-proofer run after the site is generated should be able to find...

Thanks, I'll merge it.

**Comment by sgstair** [comment]
Yeah, I had probably misread something, I think one of the sites was spelled similarly to a redirect_from and was subtly incorrect. 
When I proceeded with analysis based on the assumption that some of the warnings were incorrect (and overlapped redirect_from elements), I eventually found that none of them were wrong in this way.

**Pull request merged**
