### PR TITLE
Add a quickstart for weechat 

### PR DESCRIPTION
**Pull request by MartinDelille**
This is a work in progress to share my usage of weechat and document it.

This sum up this official documentation which is far too verby for a beginner like me.

It also lake some usefull hint.

Here is what I want to accomplish in this PR:

- [x] start weechat
- [x] connect to a server
- [x] join a channel
- [x] send a message
- [x] scroll the history

I would maybe need some help because:

1. When I send a message, it doesn't display in the feed
1. I don't know how to scroll the history

### CODE REVIEW

**Comment by wilhelmy** [comment]
1. Odd. did you join any channels?
2. Scrolling should work by using PgUp/PgDn buttons for backlog and Up/Down for input history.

**Comment by MartinDelille** [comment]
Entering the text seems to work indeed.

Scrolling doesn't work but I must precise that I'm using a macbook without PgUp/PgDn (I'm doing fn+up/down.

**Comment by wilhelmy** [comment]
https://forums.macrumors.com/threads/how-to-page-up-page-down-in-terminal.206697/#post-17531130 this post claims it's Fn+Shift+Up but I'd appreciate if you use google yourself in the future, since I can't test/verify OS X terminal weirdness :)

**Comment by MartinDelille** [comment]
Ok sorry for that.

I thought it was *Fn+Up* but it doesn't work. *Fn+Shift+Up* doesn't work either since it seems to be a *iTerm* shortcut.

I will try to investigate this but since it is an OSX specific issue I will add the *PageUp/PageDown* shortcut you provided.

**Comment by MartinDelille** [comment]
Ok I finished what I wanted to do.

You can merge if it is ok for you!

**Comment by wilhelmy** [comment]
Not trying to make you jump through extra hoops if you don't want to, but I'd appreciate some screenshots of you doing things so people get an idea what it looks like. If you don't have time I'll just merge it soon (I'm currently very busy, unfortunately).

**Comment by MartinDelille** [comment]
I'm unfortunately don't have the time right now. I created an issue to keep the idea: #88

**Pull request merged**
